
language: cpp
sudo: required
dist: bionic

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated libblas-dev libboost-all-dev libfftw3-dev libgfortran3 libhdf5-serial-dev libgmp-dev liblapack-dev libopenmpi-dev libclang-dev python-clang-6.0 python-dev python-h5py python-mako python-matplotlib python-mpi4py python-numpy python-scipy python-sphinx libjs-mathjax libnfft3-dev

install: true

script:
  - export INSTALL_DIR=$HOME/root_install # We install outside the repository
  # ===== Set up CPP2PY
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/TRIQS/cpp2py
  - mkdir cpp2py/build && cd cpp2py/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
  - make -j2 install
  - source $INSTALL_DIR/share/cpp2pyvars.sh
  # ===== Set up app4triqs and test
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DASAN=ON -DUBSAN=ON
  - export UBSAN_SYMBOLIZER_PATH=$(which llvm-symbolizer)
  - export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer)
  - export UBSAN_OPTIONS=symbolize=1:print_stacktrace=1
  - export ASAN_OPTIONS=symbolize=1:detect_leaks=0
  - export CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 && make test
